check_numpy_59 e gresit
check_numpy_86 e gresit

check_numpy_92 e gresit

check_numpy_105 e grisit facut acceptarea, lucreaza de la un simplu print

numpy_106 e gresit lucreaza doar cu gasirea la outliners, restul nu conteaza


In [ ]:
pip install sigmoid_check==0.1.3

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 30.6 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cupy-cuda12x 12.2.0 requires numpy<1.27,>=1.20, but you have numpy 2.2.0 which is incompatible.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.2.0 which is incompatible.
langchain 0.3.11 requires numpy<2,>=1.22.4; python_version < "3.12", but you have numpy 2.2.0 which is incompatible.
matplotlib 3.8.0 requires numpy<2,>=1.21, but you have numpy 2.2.0 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but 

In [ ]:
# make sure to install the latest version of sigmoid_check with pip install sigmoid_check==0.1.3
from sigmoid_check.excalibur import *

In [ ]:
# Given a list of integers `int_list`, create a NumPy array named `array_from_list`.
@check_numpy_1
def numpy_1(int_list):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    array_from_list = np.array(int_list)
    # ABOVE GOES YOUR CODE
    return {"array_from_list": array_from_list}

numpy_1()

✅ Great job! Exercise completed successfully.


In [ ]:
# Given two NumPy arrays `array1` and `array2` of the same shape, save their element-wise addition to `added_array`.
@check_numpy_2
def numpy_2(array1, array2):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    added_array = array1 + array2
    # ABOVE GOES YOUR CODE
    return {"added_array": added_array}

numpy_2()

NameError: name 'check_numpy_2' is not defined

In [ ]:
# Given two NumPy arrays `arrayA` and `arrayB`, calculate the element-wise subtraction of `arrayB` from `arrayA` and store the result in `subtracted_array`.
@check_numpy_3
def numpy_3(arrayA, arrayB):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    subtracted_array = arrayB - arrayA
    # ABOVE GOES YOUR CODE
    return {"subtracted_array": subtracted_array}

numpy_3()

✅ Great job! Exercise completed successfully.


In [ ]:
# Given two NumPy arrays `num_array1` and `num_array2` of the same shape, find their element-wise multiplication and store in `multiplied_array`.
@check_numpy_4
def numpy_4(num_array1, num_array2):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    multiplied_array = num_array1 * num_array2
    # ABOVE GOES YOUR CODE
    return {"multiplied_array": multiplied_array}

numpy_4()

✅ Great job! Exercise completed successfully.


In [ ]:
# Given two NumPy arrays `dividend_array` and `divisor_array` of the same shape, perform element-wise division and assign the result to `divided_array`.
@check_numpy_5
def numpy_5(dividend_array, divisor_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    divided_array = dividend_array / divisor_array
    # ABOVE GOES YOUR CODE
    return {"divided_array": divided_array}

numpy_5()

✅ Great job! Exercise completed successfully.


In [ ]:
# Given a NumPy array `base_array` and a scalar `exponent`, compute the element-wise exponentiation and store the result in `exponentiated_array`.
@check_numpy_6
def numpy_6(base_array, exponent):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    exponentiated_array = base_array * exponent
    # ABOVE GOES YOUR CODE
    return {"exponentiated_array": exponentiated_array}

numpy_6()

✅ Great job! Exercise completed successfully.


In [ ]:
# Given a list of numbers `float_list`, create a NumPy array named `float_array` with a float data type.
@check_numpy_7
def numpy_7(float_list):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    float_array = np.float32(float_list)
    # ABOVE GOES YOUR CODE
    return {"float_array": float_array}

numpy_7()

✅ Great job! Exercise completed successfully.


In [ ]:
# Use the list of lists `matrix_data` to create a 2-dimensional NumPy array named `matrix`.
@check_numpy_8
def numpy_8(matrix_data):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    matrix = np.array(matrix_data)
    # ABOVE GOES YOUR CODE
    return {"matrix": matrix}

numpy_8()

✅ Great job! Exercise completed successfully.


In [ ]:
# Given a NumPy array `original_array` and the new shape tuple `new_shape`, reshape the array and store it in `reshaped_array`.
@check_numpy_9
def numpy_9(original_array, new_shape):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    reshaped_array = original_array.reshape(new_shape)
    # ABOVE GOES YOUR CODE
    return {"reshaped_array": reshaped_array}

numpy_9()

✅ Great job! Exercise completed successfully.


In [ ]:
# Using NumPy's `arange`, generate an array named `range_array` from 0 to `end` with a step of `step`.
@check_numpy_10
def numpy_10(end, step):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    range_array = np.arange( 0 , end , step )
    # ABOVE GOES YOUR CODE
    return {"range_array": range_array}

numpy_10()

✅ Great job! Exercise completed successfully.


In [ ]:
# Use NumPy's `linspace` to create an array named `linspace_array` with `linspace` evenly spaced points between `start` and `stop`.
@check_numpy_11
def numpy_11(start, stop, num_points):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    linspace_array = np.linspace(start, stop )
    # ABOVE GOES YOUR CODE
    return {"linspace_array": linspace_array}

numpy_11()

✅ Great job! Exercise completed successfully.


In [ ]:
# Create a NumPy array named `zero_array` with a shape specified by `shape` filled with zeros.
@check_numpy_12
def numpy_12(shape):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    zero_array = np.zeros(shape)
    # ABOVE GOES YOUR CODE
    return {"zero_array": zero_array}

numpy_12()

✅ Great job! Exercise completed successfully.


In [ ]:
# Create a NumPy array named `ones_array` with a shape given by `shape` filled with ones.
@check_numpy_13
def numpy_13(shape):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    ones_array = np.ones (shape)
    # ABOVE GOES YOUR CODE
    return {"ones_array": ones_array}

numpy_13()

✅ Great job! Exercise completed successfully.


In [ ]:
# Given a size `n`, generate an identity matrix named `identity_matrix` of size `n x n`.
@check_numpy_14
def numpy_14(n):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    identity_matrix = np.identity(n)
    # ABOVE GOES YOUR CODE
    return {"identity_matrix": identity_matrix}

numpy_14()

✅ Great job! Exercise completed successfully.


In [ ]:
# Given a NumPy array `matrix_array`, extract its shape and assign it to `array_shape`.
@check_numpy_15
def numpy_15(matrix_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    array_shape = np.shape(matrix_array)
    # ABOVE GOES YOUR CODE
    return {"array_shape": array_shape}

numpy_15()

✅ Great job! Exercise completed successfully.


In [ ]:
# Determine the number of dimensions of the NumPy array `dim_array` and store it in `num_dimensions`.
@check_numpy_16
def numpy_16(dim_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    num_dimensions = dim_array.ndim
    # ABOVE GOES YOUR CODE
    return {"num_dimensions": num_dimensions}

numpy_16()

✅ Great job! Exercise completed successfully.


In [ ]:
# Calculate the total number of elements in the NumPy array `elements_array` and store it in `total_elements`.
@check_numpy_17
def numpy_17(elements_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    total_elements = elements_array.size
    # ABOVE GOES YOUR CODE
    return {"total_elements": total_elements}

numpy_17()

✅ Great job! Exercise completed successfully.


In [ ]:
# Assign the data type of elements in the NumPy array `type_array` to the variable `element_type`.
@check_numpy_18
def numpy_18(type_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    element_type = type_array.dtype
    # ABOVE GOES YOUR CODE
    return {"element_type": element_type}

numpy_18()

✅ Great job! Exercise completed successfully.


In [ ]:
# Compute the memory size (in bytes) of each element in the array `memory_array` and assign it to `element_size`.
@check_numpy_19
def numpy_19(memory_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    element_size = memory_array.itemsize
    # ABOVE GOES YOUR CODE
    return {"element_size": element_size}

numpy_19()

✅ Great job! Exercise completed successfully.


In [ ]:
# Convert the integer NumPy array `int_array` to a float array and save it in `float_converted_array`.
@check_numpy_20
def numpy_20(int_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    float_converted_array = np.int32(int_array)
    # ABOVE GOES YOUR CODE
    return {"float_converted_array": float_converted_array}

numpy_20()

✅ Great job! Exercise completed successfully.


In [ ]:
# Given a NumPy array `access_array` and an index `index`, assign the element at that index to `selected_element`.
@check_numpy_21
def numpy_21(access_array, index):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    selected_element = access_array[index]
    # ABOVE GOES YOUR CODE
    return {"selected_element": selected_element}

numpy_21()

✅ Great job! Exercise completed successfully.


In [ ]:
# Given a NumPy array `slicce_array`, extract a slice using `start` and `end` indices, and store it in `sliced_array`.
@check_numpy_22
def numpy_22(slice_array, start, end):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    sliced_array = slice_array[start: end]
    # ABOVE GOES YOUR CODE
    return {"sliced_array": sliced_array}

numpy_22()

✅ Great job! Exercise completed successfully.


In [ ]:
# Increase each element of `one_d_array` by 5 and store the result in `increased_array`.
@check_numpy_23
def numpy_23(one_d_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    increased_array = one_d_array + 5
    # ABOVE GOES YOUR CODE
    return {"increased_array": increased_array}

numpy_23()

[1 2 3 4 5]
[ 6  7  8  9 10]
[10 20 30 40 50]
[15 25 35 45 55]
[100 200 300 400 500]
[105 205 305 405 505]
✅ Great job! Exercise completed successfully.


In [ ]:
# Double the values in the 2D array `multi_d_array` and save it in `doubled_array`.
@check_numpy_24
def numpy_24(multi_d_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    doubled_array = multi_d_array *2
    # ABOVE GOES YOUR CODE
    return {"doubled_array": doubled_array}

numpy_24()

✅ Great job! Exercise completed successfully.


In [ ]:
# Given a NumPy array `mask_array` and a `mask_value`, create `filtered_array` containing only the elements of `mask_array` that are greater than `mask_value`.
@check_numpy_25
def numpy_25(mask_array, mask_value):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    filtered_array =[]
    mask_array = np.array(mask_array)
    filtered_array = mask_array[mask_array > mask_value]
    # ABOVE GOES YOUR CODE
    return {"filtered_array": filtered_array}

numpy_25()

✅ Great job! Exercise completed successfully.


In [ ]:
# Apply masking to the 2D array `multi_mask_array` that keeps all elements greater than the 'condition_value' and store the satisfying elements in `masked_array_2d`.
@check_numpy_26
def numpy_26(multi_mask_array, condition_value):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    # print ("multi_mask_array = ",multi_mask_array)
    # multi_mask_array = np.asarray(multi_mask_array)
    # print("mask_array=", multi_mask_array)
    masked_array_2d =  multi_mask_array[multi_mask_array > condition_value]


    # ABOVE GOES YOUR CODE
    return {"masked_array_2d": masked_array_2d}

numpy_26()

✅ Great job! Exercise completed successfully.


In [ ]:
# Calculate the sum of elements for each column of a 2D array `sum_2d_array` and store it in `column_sums`.
@check_numpy_27
def numpy_27(sum_2d_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    column_sums = np.sum(sum_2d_array, axis = 1)
    # ABOVE GOES YOUR CODE
    return {"column_sums": column_sums}

numpy_27()

✅ Great job! Exercise completed successfully.


In [ ]:
# Find the minimum value in the NumPy array `min_array` and assign it to `min_value`.
@check_numpy_28
def numpy_28(min_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    min_value = np.min(min_array)
    # ABOVE GOES YOUR CODE
    return {"min_value": min_value}

numpy_28()

✅ Great job! Exercise completed successfully.


In [ ]:
# Find the maximum value in the NumPy array `max_array` and assign it to `max_value`.
@check_numpy_29
def numpy_29(max_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    max_value = np.max(max_array)
    # ABOVE GOES YOUR CODE
    return {"max_value": max_value}

numpy_29()

✅ Great job! Exercise completed successfully.


In [ ]:
# Calculate the mean of `mean_array` and store it in `mean_value`.
@check_numpy_30
def numpy_30(mean_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    mean_value = np.mean(mean_array)
    # ABOVE GOES YOUR CODE
    return {"mean_value": mean_value}

numpy_30()

✅ Great job! Exercise completed successfully.


In [ ]:
# Calculate the standard deviation of the NumPy array `std_array` and assign it to `std_dev`.
@check_numpy_31
def numpy_31(std_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    std_dev = np.std (std_array)
    # ABOVE GOES YOUR CODE
    return {"std_dev": std_dev}

numpy_31()

✅ Great job! Exercise completed successfully.


In [ ]:
# Compute the square root of each element in `sqrt_array` using `np.sqrt()` and save the result in `sqrt_result`.
@check_numpy_32
def numpy_32(sqrt_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    sqrt_result = np.sqrt(sqrt_array)
    # ABOVE GOES YOUR CODE
    return {"sqrt_result": sqrt_result}

numpy_32()

✅ Great job! Exercise completed successfully.


In [ ]:
# Calculate the exponential of each element in `exp_array` with `np.exp()` and store it in `exp_result`.
@check_numpy_33
def numpy_33(exp_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    exp_result= np.exp(exp_array)
    # ABOVE GOES YOUR CODE
    return {"exp_result": exp_result}

numpy_33()

✅ Great job! Exercise completed successfully.


In [ ]:
# Compute the natural logarithm of each element in `log_array` with `np.log()` and save it in `log_result`.
@check_numpy_34
def numpy_34(log_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    log_result = np.log(log_array)
    # ABOVE GOES YOUR CODE
    return {"log_result": log_result}

numpy_34()

✅ Great job! Exercise completed successfully.


In [ ]:
# Calculate the sine of each element in `sin_array` using `np.sin()` and store the result in `sin_result`.
@check_numpy_35
def numpy_35(sin_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    sin_result = np.sin(sin_array)
    # ABOVE GOES YOUR CODE
    return {"sin_result": sin_result}

numpy_35()

✅ Great job! Exercise completed successfully.


In [ ]:
# Compute the cosine of `cos_array` with `np.cos()` and save it in `cos_result`.
@check_numpy_36
def numpy_36(cos_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    cos_result = np.cos(cos_array)
    # ABOVE GOES YOUR CODE
    return {"cos_result": cos_result}

numpy_36()

✅ Great job! Exercise completed successfully.


In [ ]:
# Calculate the tangent of each element in `tan_array` using `np.tan()` and save it in `tan_result`.
@check_numpy_37
def numpy_37(tan_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    tan_result = np.tan(tan_array)
    # ABOVE GOES YOUR CODE
    return {"tan_result": tan_result}

numpy_37()

✅ Great job! Exercise completed successfully.


In [ ]:
# Transpose the 2D array `transpose_array` using `np.transpose()` and store in `transposed_array`.
@check_numpy_38
def numpy_38(transpose_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    transposed_array = np.transpose(transpose_array)
    # ABOVE GOES YOUR CODE
    return {"transposed_array": transposed_array}

numpy_38()

✅ Great job! Exercise completed successfully.


In [ ]:
# Compute the dot product of `vector1` and `vector2` using `np.dot()` and assign the result to `dot_product_result`.
@check_numpy_39
def numpy_39(vector1, vector2):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    dot_product_result = np.dot(vector1, vector2 )
    # ABOVE GOES YOUR CODE
    return {"dot_product_result": dot_product_result}

numpy_39()

✅ Great job! Exercise completed successfully.


In [ ]:
# Calculate the inverse of the square matrix `square_matrix` using `np.linalg.inv()` and store it in `inverse_matrix`.
@check_numpy_40
def numpy_40(square_matrix):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    inverse_matrix = np.linalg.inv(square_matrix)
    # ABOVE GOES YOUR CODE
    return {"inverse_matrix": inverse_matrix}

numpy_40()

✅ Great job! Exercise completed successfully.


In [ ]:
# Find the determinant of the square matrix `det_matrix` using `np.linalg.det()` and assign it to `determinant_value`.
@check_numpy_41
def numpy_41(det_matrix):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    determinant_value = np.linalg.det(det_matrix)
    # ABOVE GOES YOUR CODE
    return {"determinant_value": determinant_value}

numpy_41()

✅ Great job! Exercise completed successfully.


In [ ]:
# Concatenate `array_x` and `array_y` vertically using `np.concatenate()` and save the result in `concat_vertical`.
@check_numpy_42
def numpy_42(array_x, array_y):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    concat_vertical = np.concatenate([array_x, array_y], axis=0)
    # ABOVE GOES YOUR CODE
    return {"concat_vertical": concat_vertical}

numpy_42()

✅ Great job! Exercise completed successfully.


In [ ]:
# Stack `stack_array1` and `stack_array2` horizontally using `np.hstack()` and assign it to `stacked_horizontal`.
@check_numpy_43
def numpy_43(stack_array1, stack_array2):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    stacked_horizontal = np.hstack([stack_array1, stack_array2])
    # ABOVE GOES YOUR CODE
    return {"stacked_horizontal": stacked_horizontal}

numpy_43()

✅ Great job! Exercise completed successfully.


In [ ]:
# Add a scalar `scalar_value` to each element of `broadcast_array` using broadcasting and store in `broadcast_result`.
@check_numpy_44
def numpy_44(broadcast_array, scalar_value):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    broadcast_result = broadcast_array + scalar_value
    # ABOVE GOES YOUR CODE
    return {"broadcast_result": broadcast_result}

numpy_44()

✅ Great job! Exercise completed successfully.


In [ ]:
# Given a 1D array `small_array` and a 2D array `large_array`, utilize broadcasting to add them and store the result in `broadcast_sum`.
@check_numpy_45
def numpy_45(small_array, large_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    broadcast_sum = small_array + large_array
    # ABOVE GOES YOUR CODE
    return {"broadcast_sum": broadcast_sum}

numpy_45()

✅ Great job! Exercise completed successfully.


In [ ]:
# Subtract a scalar value `scalar_sub` from each element of `two_d_array`.
@check_numpy_46
def numpy_46(two_d_array, scalar_sub):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    two_d_array = two_d_array - scalar_sub
    # ABOVE GOES YOUR CODE
    return {"two_d_array": two_d_array}

numpy_46()

✅ Great job! Exercise completed successfully.


In [ ]:
# Given dimensions `dim1`, `dim2`, and `dim3`, create a 3D NumPy array named `random_int_array` containing random integers between 0 and 10.
@check_numpy_47
def numpy_47(dim1, dim2, dim3):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    random_int_array = np.random.randint (0,10,(dim1, dim2, dim3 ))
    # ABOVE GOES YOUR CODE
    return {"random_int_array": random_int_array}

numpy_47()

✅ Great job! Exercise completed successfully.


In [ ]:
# Convert the 2D array `multi_array` into a 1D array named `flattened`.
@check_numpy_48
def numpy_48(multi_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    flattened = multi_array.ravel()
    # ABOVE GOES YOUR CODE
    return {"flattened": flattened}

numpy_48()

✅ Great job! Exercise completed successfully.


In [ ]:
# Given a NumPy array `nonzero_array`, use `np.nonzero()` to find indices of non-zero elements and assign them to `nonzero_indices`.
@check_numpy_49
def numpy_49(nonzero_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    nonzero_indices = np.nonzero(nonzero_array)
    # ABOVE GOES YOUR CODE
    return {"nonzero_indices": nonzero_indices}

numpy_49()

✅ Great job! Exercise completed successfully.


In [ ]:
# Create a diagonal matrix `diagonal_matrix` with the given 1D array `diag_elements` using `np.diag()`.
@check_numpy_50
def numpy_50(diag_elements):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    diagonal_matrix = np.diag(diag_elements)
    # ABOVE GOES YOUR CODE
    return {"diagonal_matrix": diagonal_matrix}

numpy_50()

✅ Great job! Exercise completed successfully.


In [ ]:
# Update values in `conditional_array` to `new_value` where the condition `np.where_condition` is satisfied, and save it in `updated_array`.
@check_numpy_51
def numpy_51(conditional_array, np_where_condition, new_value):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE

    # ABOVE GOES YOUR CODE
    return {"updated_array": updated_array}

numpy_51()

❗ The implementation is incorrect or the exercise was not implemented.


In [ ]:
# Given two arrays `max_array_a` and `max_array_b`, compute the element-wise maximum and store it in `element_max`.
@check_numpy_52
def numpy_52(max_array_a, max_array_b):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    element_max = np.maximum(max_array_a, max_array_b)
    # ABOVE GOES YOUR CODE
    return {"element_max": element_max}

numpy_52()

✅ Great job! Exercise completed successfully.


In [ ]:
# Calculate the cumulative sum of elements in `cumsum_array` and assign it to `cumulative_sum`.
@check_numpy_53
def numpy_53(cumsum_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    cumulative_sum = np.cumsum(cumsum_array)
    # ABOVE GOES YOUR CODE
    return {"cumulative_sum": cumulative_sum}

numpy_53()

✅ Great job! Exercise completed successfully.


In [ ]:
# Extract unique elements from the NumPy array `unique_array` and store them in `unique_elements`.
@check_numpy_54
def numpy_54(unique_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    unique_elements = np.unique(unique_array)
    # ABOVE GOES YOUR CODE
    return {"unique_elements": unique_elements}

numpy_54()

✅ Great job! Exercise completed successfully.


In [ ]:
# Sort the array `sort_array` in ascending order and assign it to `sorted_array`.
@check_numpy_55
def numpy_55(sort_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    sorted_array = np.sort(sort_array)
    # ABOVE GOES YOUR CODE
    return {"sorted_array": sorted_array}

numpy_55()

✅ Great job! Exercise completed successfully.


In [ ]:
# Compute the intersection of two arrays `intersect_array1` and `intersect_array2` and save it in `intersection`.
@check_numpy_56
def numpy_56(intersect_array1, intersect_array2):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    intersection = np.intersect1d(intersect_array1,intersect_array2 )
    # ABOVE GOES YOUR CODE
    return {"intersection": intersection}

numpy_56()

✅ Great job! Exercise completed successfully.


In [ ]:
# Join `join_array1`, `join_array2`, and `join_array3` along a new axis using `np.stack()` and store it in `joined_array`.
@check_numpy_57
def numpy_57(join_array1, join_array2, join_array3):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    joined_array = np.stack([join_array1, join_array2, join_array3], axis= 0)
    # ABOVE GOES YOUR CODE
    return {"joined_array": joined_array}

numpy_57()

✅ Great job! Exercise completed successfully.


In [ ]:
# Split `split_array` into `num_splits` parts using `np.array_split()` and assign the result to `split_parts`.
@check_numpy_58
def numpy_58(split_array, num_splits):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    split_parts = np.array_split(split_array, num_splits)
    # ABOVE GOES YOUR CODE
    return {"split_parts": split_parts}

numpy_58()

✅ Great job! Exercise completed successfully.


In [ ]:
# Count elements in `count_array` that are greater than `threshold` and assign the count to `greater_count`.
@check_numpy_59
def numpy_59(count_array, threshold):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    print ("count_array" , count_array)
    print ("threshold", threshold)
    greater_count = np.count_nonzero(count_array > threshold)
    print("greater_count", greater_count)
    # ABOVE GOES YOUR CODE
    return {"greater_count": greater_count}

numpy_59()

count_array [1 2 3 4 5]
threshold 3
greater_count 2
❗ The implementation is incorrect or the exercise was not implemented.


In [ ]:
# Rotate the 2D array `rotate_array` 90 degrees counterclockwise using `np.rot90()` and store it in `rotated_array`.
@check_numpy_60
def numpy_60(rotate_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    rotated_array = np.rot90(rotate_array)
    # ABOVE GOES YOUR CODE
    return {"rotated_array": rotated_array}

numpy_60()

✅ Great job! Exercise completed successfully.


In [ ]:
# Create an array named `random_float_array` with shape `float_shape` containing random floats between 0 and 1.
@check_numpy_61
def numpy_61(float_shape):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    random_float_array = np.random.rand(*float_shape)
    # ABOVE GOES YOUR CODE
    return {"random_float_array": random_float_array}

numpy_61()

✅ Great job! Exercise completed successfully.


In [ ]:
# Compute the median of `median_array` and store it in `median_value`.
@check_numpy_62
def numpy_62(median_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    median_value = np.median(median_array)
    # ABOVE GOES YOUR CODE
    return {"median_value": median_value}

numpy_62()

✅ Great job! Exercise completed successfully.


In [ ]:
# Given a complex NumPy array `complex_array`, extract its real and imaginary parts into `real_part` and `imag_part`.
@check_numpy_63
def numpy_63(complex_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    real_part = np.real(complex_array)
    imag_part = np.imag(complex_array)
    # ABOVE GOES YOUR CODE
    return {"real_part": real_part, "imag_part": imag_part}

numpy_63()

✅ Great job! Exercise completed successfully.


In [ ]:
# Normalize the array `norm_array` to have values between 0 and 1, storing the result in `normalized_array`.
@check_numpy_64

def numpy_64(norm_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    min_value = np.min(norm_array)
    max_value = np.max(norm_array)
    normalized_array = (norm_array - min_value) / (max_value - min_value)
    # ABOVE GOES YOUR CODE
    return {"normalized_array": normalized_array}

numpy_64()

✅ Great job! Exercise completed successfully.


In [ ]:
# Replace negative elements in `replace_array` with `new_value` using `np.where()` and store in `replaced_array`.
@check_numpy_65
def numpy_65(replace_array, new_value):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    replaced_array = np.where(replace_array > 0, replace_array , new_value)
    # ABOVE GOES YOUR CODE
    return {"replaced_array": replaced_array}

numpy_65()

✅ Great job! Exercise completed successfully.


In [ ]:
# Calculate the row-wise total sum for `axis_sum_array` and assign the output to `row_sums`.
@check_numpy_66
def numpy_66(axis_sum_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    row_sums = np.sum(axis_sum_array, axis= 1)
    # ABOVE GOES YOUR CODE
    return {"row_sums": row_sums}

numpy_66()

✅ Great job! Exercise completed successfully.


In [ ]:
# Produce a matrix `random_matrix` with `matrix_shape` dimensions and random integers from 0 to 100.
@check_numpy_67
def numpy_67(matrix_shape):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    random_matrix = np.random.rand(*matrix_shape)
    # ABOVE GOES YOUR CODE
    return {"random_matrix": random_matrix.shape, "random_values": np.any((random_matrix < 0) | (random_matrix > 100))}

numpy_67()

✅ Great job! Exercise completed successfully.


In [ ]:
# Raise each element in `base_power_array` to a power specified in `exp_power_array`, element-wise, and store in `powered_array`.
@check_numpy_68
def numpy_68(base_power_array, exp_power_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    powered_array = np.power(base_power_array, exp_power_array)
    # ABOVE GOES YOUR CODE
    return {"powered_array": powered_array}

numpy_68()

✅ Great job! Exercise completed successfully.


In [ ]:
# Detect NaN elements within `nan_array` using `np.isnan()` and assign the position to `nan_indices`.
@check_numpy_69
def numpy_69(nan_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    nan_indices = np.isnan(nan_array)
    # ABOVE GOES YOUR CODE
    return {"nan_indices": nan_indices}

numpy_69()

✅ Great job! Exercise completed successfully.


In [ ]:
# Replace `NaN` values in `nan_replace_array` with `specific_value` and create `nan_replaced_array`.
@check_numpy_70
def numpy_70(nan_replace_array, specific_value):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    nan_replaced_array = nan_replaced_array = np.nan_to_num(nan_replace_array, nan=specific_value)
    # ABOVE GOES YOUR CODE
    return {"nan_replaced_array": nan_replaced_array}

numpy_70()

✅ Great job! Exercise completed successfully.


In [ ]:
# Construct an upper triangular version of `triangular_matrix` using `np.triu()`.
@check_numpy_71
def numpy_71(triangular_matrix):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    triangular_matrix = np.triu(triangular_matrix)
    # ABOVE GOES YOUR CODE
    return {"upper_triangular": triangular_matrix}

numpy_71()

✅ Great job! Exercise completed successfully.


In [ ]:
# Calculate the `percentile_value` percentile of elements in `percentile_array` and set the result to `percentile_result`.
@check_numpy_72
def numpy_72(percentile_array, percentile_value):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    percentile_result = np.percentile(percentile_array, percentile_value)
    # ABOVE GOES YOUR CODE
    return {"percentile_result": percentile_result}

numpy_72()

✅ Great job! Exercise completed successfully.


In [ ]:
# Calculate the trace (sum of diagonals) of the matrix `trace_matrix` using `np.trace()`.
@check_numpy_73
def numpy_73(trace_matrix):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    trace_value = np.trace(trace_matrix)
    # ABOVE GOES YOUR CODE
    return {"trace_value": trace_value}

numpy_73()

✅ Great job! Exercise completed successfully.


In [ ]:
# Compute the index of the maximum value in `index_max_array` and store it in `max_index`.
@check_numpy_74
def numpy_74(index_max_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    max_index = np.argmax(index_max_array)
    # ABOVE GOES YOUR CODE
    return {"max_index": max_index}

numpy_74()

✅ Great job! Exercise completed successfully.


In [ ]:
# Find the index of the minimum value in `index_min_array` and assign it to `min_index`.
@check_numpy_75
def numpy_75(index_min_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    min_index = np.argmin(index_min_array)
    # ABOVE GOES YOUR CODE
    return {"min_index": min_index}

numpy_75()

✅ Great job! Exercise completed successfully.


In [ ]:
# Perform an element-wise comparison of `compare_array1` and `compare_array2` using `np.equal()` and assign to `comparison_result`.
@check_numpy_76
def numpy_76(compare_array1, compare_array2):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    comparison_result = np.equal(compare_array1 , compare_array2)
    # ABOVE GOES YOUR CODE
    return {"comparison_result": comparison_result}

numpy_76()

✅ Great job! Exercise completed successfully.


In [ ]:
# Perform the matrix multiplication between two arrays `mat_mult_a` and `mat_mult_b` and store the result in `matrix_product`.
@check_numpy_77
def numpy_77(mat_mult_a, mat_mult_b):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    matrix_product = np.multiply(mat_mult_a, mat_mult_b)
    # ABOVE GOES YOUR CODE
    return {"matrix_product": matrix_product}

numpy_77()

✅ Great job! Exercise completed successfully.


In [ ]:
# Extract the diagonal of `diag_matrix` using `np.diag()` and store it in `matrix_diagonal`.
@check_numpy_78
def numpy_78(diag_matrix):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    matrix_diagonal = np.diag(diag_matrix)
    # ABOVE GOES YOUR CODE
    return {"matrix_diagonal": matrix_diagonal}

numpy_78()

✅ Great job! Exercise completed successfully.


In [ ]:
# Clip `clip_array` such that all its values fall between `min_clip` and `max_clip`, saving the result in `clipped_array`.
@check_numpy_79
def numpy_79(clip_array, min_clip, max_clip):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    clipped_array = np.clip(clip_array, min_clip, max_clip)
    # ABOVE GOES YOUR CODE
    return {"clipped_array": clipped_array}

numpy_79()

✅ Great job! Exercise completed successfully.


In [ ]:
# Flip `flip_array` along the specified axis `flip_axis` using `np.flip()` and assign to `flipped_array`.
@check_numpy_80
def numpy_80(flip_array, flip_axis):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    flipped_array= np.flip(flip_array, flip_axis)
    # ABOVE GOES YOUR CODE
    return {"flipped_array": flipped_array}

numpy_80()

✅ Great job! Exercise completed successfully.


In [ ]:
# Simulate rolling a six-sided die `num_rolls` times to generate an array `dice_rolls`.
@check_numpy_81
def numpy_81(num_rolls):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    dice_rolls = np.random.rand(1,6)
    # ABOVE GOES YOUR CODE
    return {"dice_rolls": dice_rolls}

numpy_81()

✅ Great job! Exercise completed successfully.


In [ ]:
# Given two arrays `logical_array_a` and `logical_array_b`, perform a logical `and` operation and save result in `logical_and_result`.
@check_numpy_82
def numpy_82(logical_array_a, logical_array_b):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    logical_and_result = logical_array_a & logical_array_b
    # ABOVE GOES YOUR CODE
    return {"logical_and_result": logical_and_result}

numpy_82()

✅ Great job! Exercise completed successfully.


In [ ]:
# Reverse the elements in `reverse_array` and store the result in `reversed_array`.
@check_numpy_83
def numpy_83(reverse_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    reversed_array = np.flip(reverse_array)
    # ABOVE GOES YOUR CODE
    return {"reversed_array": reversed_array}

numpy_83()

✅ Great job! Exercise completed successfully.


In [ ]:
# Compute the cross-product of vectors `vector_a` and `vector_b` and store it in `cross_product_result`.
@check_numpy_84
def numpy_84(vector_a, vector_b):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    cross_product_result = np.cross(vector_a, vector_b)
    # ABOVE GOES YOUR CODE
    return {"cross_product_result": cross_product_result}

numpy_84()

✅ Great job! Exercise completed successfully.


In [ ]:
# Use `np.vstack()` to vertically stack `vert_stack_a` and `vert_stack_b` and assign to `vertically_stacked`.
@check_numpy_85
def numpy_85(vert_stack_a, vert_stack_b):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    vertically_stacked = np.vstack((vert_stack_a, vert_stack_b))
    # ABOVE GOES YOUR CODE
    return {"vertically_stacked": vertically_stacked}

numpy_85()

✅ Great job! Exercise completed successfully.


In [ ]:
# Create a `checkered_matrix` of size `check_size` with alternating zeros and ones.
@check_numpy_86
def numpy_86(check_size):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    print ("check_size  ", check_size)
    checkered_matrix = np.indices((check_size, check_size)).sum(axis=0) % 2
    print ("checkered_matrix  ", checkered_matrix)
    # ABOVE GOES YOUR CODE
    return {"checkered_matrix": checkered_matrix}

numpy_86()

check_size   (3, 3)
❗ The implementation is incorrect or the exercise was not implemented.


In [ ]:
# Determine the rank of `rank_matrix` using `np.linalg.matrix_rank()`.
@check_numpy_87
def numpy_87(rank_matrix):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    matrix_rank = np.linalg.matrix_rank(rank_matrix)
    # ABOVE GOES YOUR CODE
    return {"matrix_rank": matrix_rank}

numpy_87()

✅ Great job! Exercise completed successfully.


In [ ]:
# Extract all non-diagonal elements from `non_diag_matrix` and store them in `off_diagonal`.
@check_numpy_88
def numpy_88(non_diag_matrix):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    mask = np.ones(non_diag_matrix.shape, dtype=bool)
    np.fill_diagonal(mask, 0)
    off_diagonal = non_diag_matrix[mask]
    # ABOVE GOES YOUR CODE
    return {"off_diagonal": off_diagonal}

numpy_88()

✅ Great job! Exercise completed successfully.


In [ ]:
# Create a boolean mask `boolean_mask` for the array `mask_less_array` with elements less than `threshold_value`.
@check_numpy_89
def numpy_89(mask_less_array, threshold_value):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    boolean_mask = mask_less_array <threshold_value
    # ABOVE GOES YOUR CODE
    return {"boolean_mask": boolean_mask}

numpy_89()

✅ Great job! Exercise completed successfully.


In [ ]:
# Compute the cumulative product of `cumprod_array` and assign the result to `cumulative_product`.
@check_numpy_90
def numpy_90(cumprod_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    cumulative_product = np.cumsum(cumprod_array)
    # ABOVE GOES YOUR CODE
    return {"cumulative_product": cumulative_product}

numpy_90()

✅ Great job! Exercise completed successfully.


In [ ]:
# Calculate the absolute differences between `abs_diff_a1` and `abs_diff_a2`, storing the result in `absolute_diff`.
@check_numpy_91
def numpy_91(abs_diff_a1, abs_diff_a2):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    absolute_diff = np.abs(abs_diff_a1 - abs_diff_a2)
    # ABOVE GOES YOUR CODE
    return {"absolute_diff": absolute_diff}

numpy_91()

✅ Great job! Exercise completed successfully.


In [ ]:
# Check if `elem_equal_a` and `elem_equal_b` are element-wise equal and store the boolean result in `elementwise_equality`.
@check_numpy_92
def numpy_92(elem_equal_a, elem_equal_b):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    print (elem_equal_a)
    print (elem_equal_b)
    elementwise_equality = []
    elementwise_equality = np.equal(elem_equal_a, elem_equal_b)
    print(elementwise_equality)
    # ABOVE GOES YOUR CODE
    return {"elementwise_equality": elementwise_equality}

numpy_92()

[1 2 3 4 5]
[1 2 3 4 5]
[ True  True  True  True  True]
❗ The implementation is incorrect or the exercise was not implemented.


In [ ]:
# Create `filtered_within_range` by extracting values from `range_filter_array` that are between `lower_bound` and `upper_bound`.
@check_numpy_93
def numpy_93(range_filter_array, lower_bound, upper_bound):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE

    start = np.searchsorted(range_filter_array, lower_bound, 'left')
    end = np.searchsorted(range_filter_array, upper_bound, 'right')
    filtered_within_range = np.arange(start, end)
    print (filtered_within_range)
    # ABOVE GOES YOUR CODE
    return {"filtered_within_range": filtered_within_range}

numpy_93()

[1 2 3]
[1 2 3]
[1 2 3]
✅ Great job! Exercise completed successfully.


In [ ]:
# Multiply a 1D array `broad_1d` with each row of a 2D array `broad_2d`, and store the result in `broadcast_mult_result`.
@check_numpy_94
def numpy_94(broad_1d, broad_2d):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    broadcast_mult_result = broad_1d * broad_2d
    # ABOVE GOES YOUR CODE
    return {"broadcast_mult_result": broadcast_mult_result}

numpy_94()

✅ Great job! Exercise completed successfully.


In [ ]:
# Multiply a 1D array `broad_1d` with each row of a 2D array `broad_2d`, and store the result in `broadcast_mult_result`.
@check_numpy_95
def numpy_95(broad_1d, broad_2d):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    broadcast_mult_result = broad_1d * broad_2d
    # ABOVE GOES YOUR CODE
    return {"broadcast_mult_result": broadcast_mult_result}

numpy_95()

✅ Great job! Exercise completed successfully.


In [ ]:
# Apply logarithm base 10 to `log10_array` using `np.log10()` and save the result in `log10_result`.
@check_numpy_96
def numpy_96(log10_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    log10_result = np.log10(log10_array)
    # ABOVE GOES YOUR CODE
    return {"log10_result": log10_result}

numpy_96()

✅ Great job! Exercise completed successfully.


In [ ]:
# Form a lower triangular matrix from `lower_tri_matrix` using `np.tril()`.
@check_numpy_97
def numpy_97(lower_tri_matrix):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    lower_triangular = np.tril(lower_tri_matrix)
    # ABOVE GOES YOUR CODE
    return {"lower_triangular": lower_triangular}

numpy_97()

✅ Great job! Exercise completed successfully.


In [ ]:
# Determine if there are any `True` elements in `bool_array`, assigning the result to `any_true`.
@check_numpy_98
def numpy_98(bool_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    any_true = np.any(bool_array)
    # ABOVE GOES YOUR CODE
    return {"any_true": any_true}

numpy_98()

✅ Great job! Exercise completed successfully.


In [ ]:
# Check if all elements in `bool_check_array` are `True`, and store the result in `all_true`.
@check_numpy_99
def numpy_99(bool_check_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    all_true = np.all(bool_check_array)
    # ABOVE GOES YOUR CODE
    return {"all_true": all_true}

numpy_99()

✅ Great job! Exercise completed successfully.


In [ ]:
# Given two vectors `cos_vector_a` and `cos_vector_b`, calculate the cosine similarity and store it in `cosine_similarity`.
@check_numpy_100
def numpy_100(cos_vector_a, cos_vector_b):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    dot_product = np.dot(cos_vector_a, cos_vector_b)

    norm_a = np.linalg.norm(cos_vector_a)
    norm_b = np.linalg.norm(cos_vector_b)

    if norm_a == 0 or norm_b == 0:
        cosine_similarity = 0.0
    else:
        cosine_similarity = dot_product / (norm_a * norm_b)
    # ABOVE GOES YOUR CODE
    return {"cosine_similarity": cosine_similarity}

numpy_100()

✅ Great job! Exercise completed successfully.


In [ ]:
# Create a function named `reverse_sort_numpy` that takes a NumPy array `arr`, reverses it, removes duplicate elements using NumPy, and returns a sorted version of the array.
@check_numpy_101
def numpy_101():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def reverse_sort_numpy(arr):
        # Step 1: Reverse the array
        reversed_arr = arr[::-1]

        # Step 2: Remove duplicate elements
        unique_arr = np.unique(reversed_arr)

        # Step 3: Sort the resulting array
        sorted_arr = np.sort(unique_arr)

        return sorted_arr
    # ABOVE GOES YOUR CODE
    return {"reverse_sort_numpy": reverse_sort_numpy}

numpy_101()

✅ Great job! Exercise completed successfully.


In [ ]:
# Write a function `normalize_scale_numpy` that takes a NumPy array `arr` and a range `min_val`, `max_val`. Use NumPy to normalize the array to the range [0, 1], then scale it to the given range, and return the resulting array.
@check_numpy_102
def numpy_102():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def normalize_scale_numpy(arr, min_val, max_val):
      new_arr = []
      dif = min_val - max_val
      dif_arr = max(arr) - min(arr)
      for n in arr:
        new_arr.append(((n-min(arr)/dif)*dif_arr)+min_val)
    # ABOVE GOES YOUR CODE
    return {"normalize_scale_numpy": normalize_scale_numpy}

numpy_102()

✅ Great job! Exercise completed successfully.


In [ ]:
# Develop a function `filter_average_numpy` that takes a NumPy array `data` and a threshold `limit`. Use NumPy to filter elements greater than `limit`, compute their average, and return this average.
@check_numpy_103
def numpy_103():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def filter_average_numpy(data, limit):
      # V1
      # limit_arr = []
      # for n in data:
      #   if n>limit : limit_arr.append(n)
      # return np.average(limit_arr)
      # V2
      filtered_data = data[data > limit]
      return np.average(filtered_data) if filtered_data.size > 0 else float('nan')
    # ABOVE GOES YOUR CODE
    return {"filter_average_numpy": filter_average_numpy}

numpy_103()

✅ Great job! Exercise completed successfully.


In [ ]:
# Create a function `capitalize_count_numpy` that converts a NumPy array of strings `sentence_array` to capitalize each string's first letter, counts the number of elements, and returns a tuple containing the modified array and the count.
@check_numpy_104
def numpy_104():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def capitalize_count_numpy(sentence_array):
      new_arr =  np.char.capitalize(sentence_array)
      return new_arr

    # ABOVE GOES YOUR CODE
    return {"capitalize_count_numpy": capitalize_count_numpy}

numpy_104()

✅ Great job! Exercise completed successfully.


In [ ]:
from re import S
# Implement a function `clean_categorize_numpy` that processes a NumPy array of strings `items` by stripping spaces and converting to lowercase with NumPy operations, classifying them into 'short' if under 5 characters or 'long' otherwise, returning the counts in a dictionary.
@check_numpy_105
def numpy_105():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def clean_categorize_numpy (items):
      #print(items)
      new_arr = np.char.lower(items)
      new_arr = np.char.strip(new_arr)
      #print(new_arr)
      categorized_arr = np.where(np.char.str_len(new_arr) < 5, "short", "long")
      unique, counts = np.unique(categorized_arr, return_counts=True)
      count_dict = dict(zip(unique, counts))
      #print(count_dict)
      return count_dict

    # ABOVE GOES YOUR CODE
    return {"clean_categorize_numpy": clean_categorize_numpy}

numpy_105()

✅ Great job! Exercise completed successfully.


In [ ]:
# Write a function `remove_outliers_stats_numpy` that takes a NumPy array `num_array`, removes outliers more than two standard deviations from the mean using NumPy, and returns a dictionary with 'mean', 'std', and 'filtered' keys.
@check_numpy_106
def numpy_106():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def remove_outliers_stats_numpy(num_array):
      q1 = np.percentile(num_array,25)
      q4 = np.percentile(num_array,75)
      # print(q1)
      # print(q4)
      # print(num_array)
      iqr = q4 - q1
      lower_part = q1 - 1.5 * iqr
      upper_part = q4 - 1.5 * iqr
      outliner = num_array
      new_arr = [n for n in ]
    # ABOVE GOES YOUR CODE
    return {"remove_outliers_stats_numpy": remove_outliers_stats_numpy}

numpy_106()

12.0
12.75
[ 10  12  12  13  12 100]
6.0
8.0
[   5    6    7    8 1000]
14.25
15.0
[  15   16   15   14   15 -300]
✅ Great job! Exercise completed successfully.


In [ ]:
# Create a function `unique_sorted_numpy` that accepts a NumPy array `word_arr`. Use NumPy to remove duplicates, sort them alphabetically, and return the sorted array.
@check_numpy_107
def numpy_107():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE

    # ABOVE GOES YOUR CODE
    return {"unique_sorted_numpy": unique_sorted_numpy}

numpy_107()

❗ The implementation is incorrect or the exercise was not implemented.


In [ ]:
# Implement a function `format_join_numpy` that takes a NumPy array of strings `words_array`, uses NumPy to title case each word, filter words less than 4 characters, and joins them with a hyphen, returning the final string.
@check_numpy_108
def numpy_108():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE

    # ABOVE GOES YOUR CODE
    return {"format_join_numpy": format_join_numpy}

numpy_108()

❗ The implementation is incorrect or the exercise was not implemented.


In [ ]:
# Write a function `classify_numbers_numpy` that takes a NumPy array `nums`. Use NumPy functions to detect prime numbers and separate them from non-prime numbers, returning both as arrays.
@check_numpy_109
def numpy_109():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE

    # ABOVE GOES YOUR CODE
    return {"classify_numbers_numpy": classify_numbers_numpy}

numpy_109()

❗ The implementation is incorrect or the exercise was not implemented.


In [ ]:
# Develop a function `flatten_filter_numpy` that accepts a NumPy array of arrays `list_of_arrays`, flattens it using NumPy, filters out numbers less than 10 using NumPy, and returns the filtered flat array.
@check_numpy_110
def numpy_110():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE

    # ABOVE GOES YOUR CODE
    return {"flatten_filter_numpy": flatten_filter_numpy}

numpy_110()

❗ The implementation is incorrect or the exercise was not implemented.


In [ ]:
# Create a function `square_filter_negatives_numpy` that takes a NumPy array `arr`, squares each element using NumPy array operations, removes negative elements, and returns the resulting array.
@check_numpy_111
def numpy_111():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE

    # ABOVE GOES YOUR CODE
    return {"square_filter_negatives_numpy": square_filter_negatives_numpy}

numpy_111()

❗ The implementation is incorrect or the exercise was not implemented.


In [ ]:
# Implement a function `divide_round_numpy` that takes a NumPy array `values` and a divisor `d`. Divide each element using NumPy, round to two decimal places, and return the resulting array.
@check_numpy_112
def numpy_112():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE

    # ABOVE GOES YOUR CODE
    return {"divide_round_numpy": divide_round_numpy}

numpy_112()

❗ The implementation is incorrect or the exercise was not implemented.


In [ ]:
# Write a function `zip_sum_numpy` that takes two NumPy arrays `array1` and `array2`, adds each corresponding element (pair) using NumPy, and returns a new array of these sums.
@check_numpy_113
def numpy_113():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE

    # ABOVE GOES YOUR CODE
    return {"zip_sum_numpy": zip_sum_numpy}

numpy_113()

❗ The implementation is incorrect or the exercise was not implemented.


In [ ]:
# Create a function `binary_classification_numpy` that takes an array `classes` with values `0` and `1`. Use NumPy to count each, calculate their percentages, and return a dictionary with this data.
@check_numpy_114
def numpy_114():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE

    # ABOVE GOES YOUR CODE
    return {"binary_classification_numpy": binary_classification_numpy}

numpy_114()

❗ The implementation is incorrect or the exercise was not implemented.


In [ ]:
# Develop a function `parse_convert_dates_numpy` that processes a NumPy array of date strings `date_strs` in `MM/DD/YYYY` format, converting them into `YYYY-MM-DD` using NumPy, sorting them, and returning the sorted array.
@check_numpy_115
def numpy_115():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE

    # ABOVE GOES YOUR CODE
    return {"parse_convert_dates_numpy": parse_convert_dates_numpy}

numpy_115()

❗ The implementation is incorrect or the exercise was not implemented.


In [ ]:
# Implement a function `interleave_double_numpy` that accepts two NumPy arrays `arr1` and `arr2`. Use NumPy to interleave elements, double elements from `arr2`, and return the final array.
@check_numpy_116
def numpy_116():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE

    # ABOVE GOES YOUR CODE
    return {"interleave_double_numpy": interleave_double_numpy}

numpy_116()

❗ The implementation is incorrect or the exercise was not implemented.


In [ ]:
# Write a function `group_count_numpy` that takes a NumPy array of strings `str_arr`. Use NumPy to group by length, calculate the occurrence count of each length, and return a dictionary with lengths as keys and counts as values.
@check_numpy_117
def numpy_117():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE

    # ABOVE GOES YOUR CODE
    return {"group_count_numpy": group_count_numpy}

numpy_117()

❗ The implementation is incorrect or the exercise was not implemented.


In [ ]:
# Create a function `remove_false_combine_numpy` that processes two NumPy boolean arrays `bool_arr1` and `bool_arr2`. Remove `False` entries using NumPy, concatenate them, and return the combined array.
@check_numpy_118
def numpy_118():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE

    # ABOVE GOES YOUR CODE
    return {"remove_false_combine_numpy": remove_false_combine_numpy}

numpy_118()

❗ The implementation is incorrect or the exercise was not implemented.


In [ ]:
# Develop a function `check_palindrome_reverse_numpy` that takes a NumPy array of strings `strs`, uses NumPy to filter out non-alphabetic, checks for palindromes, and returns the strings in reverse order.
@check_numpy_119
def numpy_119():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE

    # ABOVE GOES YOUR CODE
    return {"check_palindrome_reverse_numpy": check_palindrome_reverse_numpy}

numpy_119()

❗ The implementation is incorrect or the exercise was not implemented.


In [ ]:
# Implement a function `find_duplicates_unique_numpy` that accepts a NumPy array `elements`, identifies duplicates using NumPy, separates from unique elements, and returns a tuple of duplicate and unique arrays.
@check_numpy_120
def numpy_120():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE

    # ABOVE GOES YOUR CODE
    return {"find_duplicates_unique_numpy": find_duplicates_unique_numpy}

numpy_120()

❗ The implementation is incorrect or the exercise was not implemented.


In [ ]:
# Write a function `scale_match_numpy` that takes two NumPy arrays `arr_a` and `arr_b`, scales each by their respective maximum with NumPy, and returns `True` if they are identical, otherwise `False`.
@check_numpy_121
def numpy_121():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE

    # ABOVE GOES YOUR CODE
    return {"scale_match_numpy": scale_match_numpy}

numpy_121()

❗ The implementation is incorrect or the exercise was not implemented.


In [ ]:
# Create a function `calculate_ratios_sort_numpy` that takes two NumPy arrays `numers` and `denoms`. Calculate ratios using NumPy, sort them, and return a new array of sorted ratios.
@check_numpy_122
def numpy_122():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE

    # ABOVE GOES YOUR CODE
    return {"calculate_ratios_sort_numpy": calculate_ratios_sort_numpy}

numpy_122()

❗ The implementation is incorrect or the exercise was not implemented.


In [ ]:
# Develop a function `decode_filter_numpy` that processes a NumPy array `codes`, decodes using NumPy string operations, filters messages containing digits, and returns the cleaned array.
@check_numpy_123
def numpy_123():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE

    # ABOVE GOES YOUR CODE
    return {"decode_filter_numpy": decode_filter_numpy}

numpy_123()

❗ The implementation is incorrect or the exercise was not implemented.


In [ ]:
# Implement a function `sync_sum_json_numpy` that takes two JSON-like dictionaries `data1` and `data2`, synchronizes with NumPy by common keys, sums values, and returns the resulting dictionary.
@check_numpy_124
def numpy_124():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE

    # ABOVE GOES YOUR CODE
    return {"sync_sum_json_numpy": sync_sum_json_numpy}

numpy_124()

❗ The implementation is incorrect or the exercise was not implemented.


In [ ]:
# Write a function `tokenize_compare_numpy` that takes two NumPy string arrays `para1` and `para2`, tokenizes using NumPy, calculates the set difference with NumPy, and returns a list of unique words in one array.
@check_numpy_125
def numpy_125():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE

    # ABOVE GOES YOUR CODE
    return {"tokenize_compare_numpy": tokenize_compare_numpy}

numpy_125()

❗ The implementation is incorrect or the exercise was not implemented.
